version: '3'
services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: statustracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
